### ISSUE TITLE
Exception during restore process

### ISSUE THREAD

**Issue by jrchamp** [jrchamp/moodle-mod_zoom#377]
When restoring a course, if there is a Zoom activity but the mod_zoom plugin has not been configured, an Exception will be thrown that halts the course restore process.

```
Zoom webservice error: Zoom API key not found.:
#0 mod/zoom/backup/moodle2/restore_zoom_stepslib.php(60): mod_zoom_webservice->__construct()
#1 backup/util/plan/restore_structure_step.class.php(137): restore_zoom_activity_structure_step->process_zoom()
#2 backup/util/helper/restore_structure_parser_processor.class.php(121): restore_structure_step->process()
```

**Comment by jrchamp** [comment]
The restore processes don't gracefully handle exceptions and have a tendency to leave instructors with either a partially complete or completely unusable course. The assumption must be that we are expected to gracefully handle this ourselves, so even if we can't connect to the Zoom API at all, we should try and do as much as we can to leave the course in a viable state. After that point, any incomplete Zoom activity already has a mechanism for fixing that issue.
