### ISSUE TITLE
Exception thrown during course copy if URL in zoom activity is not valid.

### ISSUE THREAD

**Issue by david-edunao** [jrchamp/moodle-mod_zoom#428]
Hi,

We encounters an issue during an asynchronous course copy causing by the Moodle mod_zoom plugin.
If an URL inside an activity of this course is not valid, the course fails to copy.

See this stack trace for more information :

```
Fri Nov 4 17:54:46 CET 2022: Course copy: Processing asynchronous course copy for course id: 349
Fri Nov 4 17:54:46 CET 2022: Course copy: Backing up course, id: 349
Fri Nov 4 17:54:49 CET 2022: Course copy: Restoring into course, id: 444
Fri Nov 4 17:54:55 CET 2022: ... used 11885 dbqueries
Fri Nov 4 17:54:55 CET 2022: ... used 8.7120780944824 seconds
Fri Nov 4 17:54:55 CET 2022: Adhoc task failed: coretaskasynchronous_copy_task,La ressource n'existe pas, #0 serverpath/mod/zoom/classes/webservice.php(636): mod_zoom_webservice->_make_call()
Fri Nov 4 17:54:55 CET 2022: #1 serverpath/mod/zoom/backup/moodle2/restore_zoom_stepslib.php(70): mod_zoom_webservice->create_meeting()
Fri Nov 4 17:54:55 CET 2022: #2 serverpath/backup/util/plan/restore_structure_step.class.php(137): restore_zoom_activity_structure_step->process_zoom()
Fri Nov 4 17:54:55 CET 2022: #3 serverpath/backup/util/helper/restore_structure_parser_processor.class.php(121): restore_structure_step->process()
Fri Nov 4 17:54:55 CET 2022: #4 serverpath/backup/util/xml/parser/processors/grouped_parser_processor.class.php(178): restore_structure_parser_processor->dispatch_chunk()
Fri Nov 4 17:54:55 CET 2022: #5 serverpath/backup/util/helper/restore_structure_parser_processor.class.php(109): grouped_parser_processor->postprocess_chunk()
Fri Nov 4 17:54:55 CET 2022: #6 serverpath/backup/util/xml/parser/processors/simplified_parser_processor.class.php(148): restore_structure_parser_processor->postprocess_chunk>
Fri Nov 4 17:54:55 CET 2022: #7 serverpath/backup/util/xml/parser/processors/progressive_parser_processor.class.php(92): simplified_parser_processor->process_chunk()
Fri Nov 4 17:54:55 CET 2022: #8 serverpath/backup/util/xml/parser/progressive_parser.class.php(190): progressive_parser_processor->receive_chunk()
Fri Nov 4 17:54:55 CET 2022: #9 serverpath/backup/util/xml/parser/progressive_parser.class.php(278): progressive_parser->publish()
Fri Nov 4 17:54:55 CET 2022: #10 [internal function]: progressive_parser->end_tag()
Fri Nov 4 17:54:55 CET 2022: #11 serverpath/backup/util/xml/parser/progressive_parser.class.php(179): xml_parse()
Fri Nov 4 17:54:55 CET 2022: #12 serverpath/backup/util/xml/parser/progressive_parser.class.php(158): progressive_parser->parse()
Fri Nov 4 17:54:55 CET 2022: #13 serverpath/backup/util/plan/restore_structure_step.class.php(110): progressive_parser->process()
Fri Nov 4 17:54:55 CET 2022: #14 serverpath/backup/util/plan/base_task.class.php(181): restore_structure_step->execute()
Fri Nov 4 17:54:55 CET 2022: #15 serverpath/backup/moodle2/restore_activity_task.class.php(219): base_task->execute()
Fri Nov 4 17:54:55 CET 2022: #16 serverpath/backup/util/plan/base_plan.class.php(191): restore_activity_task->execute()
Fri Nov 4 17:54:55 CET 2022: #17 serverpath/backup/util/plan/restore_plan.class.php(168): base_plan->execute()
Fri Nov 4 17:54:55 CET 2022: #18 serverpath/backup/controller/restore_controller.class.php(408): restore_plan->execute()
Fri Nov 4 17:54:55 CET 2022: #19 serverpath/lib/classes/task/asynchronous_copy_task.php(139): restore_controller->execute_plan()
Fri Nov 4 17:54:55 CET 2022: #20 serverpath/lib/cronlib.php(341): coretaskasynchronous_copy_task->execute()
Fri Nov 4 17:54:55 CET 2022: #21 serverpath/lib/cronlib.php(198): cron_run_inner_adhoc_task()
Fri Nov 4 17:54:55 CET 2022: #22 serverpath/lib/cronlib.php(76): cron_run_adhoc_tasks()
Fri Nov 4 17:54:55 CET 2022: #23 serverpath/admin/cli/cron.php(178): cron_run()
Fri Nov 4 17:54:55 CET 2022: #24 {main}
```

Exception message is "La ressource n'existe pas", french translation of "Resource not found" that we think is the response message from "zoom_not_found_exception" here :

```
$response = $this->_make_curl_call($curl, $method, $url, $data);

if ($curl->get_errno()) {
    throw new moodle_exception('errorwebservice', 'mod_zoom', '', $curl->error);
}

$response = json_decode($response);

$httpstatus = $curl->get_info()['http_code'];
if ($httpstatus >= 400) {
    switch($httpstatus) {
        case 400:
            throw new zoom_bad_request_exception($response->message, $response->code);
        case 404:
            throw new zoom_not_found_exception($response->message, $response->code);
```

The expected behavior is that a course copy can be done even if an URL inside one of its zoom activity is no longer valid.
Thanks in advance,
David

**Comment by jrchamp** [comment]
Hi @david-edunao 

Thank you for reporting this issue. Which version of the mod_zoom plugin are you using? In v4.2, code was added that should catch this issue. (via #328)

**Comment by smbader** [comment]
Hey @david-edunao,

I just wanted to check-in and see if you are still experiencing this issue. I'm going to close this issue in hopes that all is well now but if you are still experiencing the problem, feel free to re-open this issue.

Steve
