### ISSUE TITLE
Using admin/cli/restore_backup.php doesn't work with activities with dates

### ISSUE THREAD

**Issue by danowar2k** [jrchamp/moodle-mod_zoom#534]
Moodle creates calendar events when activity end dates are set (see https://tracker.moodle.org/browse/MDL-62944).

mod_zoom always checks for the appropriate capability when creating a calendar event, see https://github.com/ncstate-delta/moodle-mod_zoom/blob/c7dba4307c31ccf894914e46aca184d77ea6492b/lib.php#L553

When using the CLI script **admin/cli/restore_backup.php** to restore a course with a mod_zoom activity with dates set, the script doesn't set $USER (see https://tracker.moodle.org/browse/MDL-79857). When the checks happen, it doesn't find a user so probably assumes no one is logged in, so it fails with an error:

```
#0 /repositories/dev/Moodle283feu/moodle/calendar/lib.php(958): calendar_event->update(Object(stdClass), true)
#1 /repositories/dev/Moodle283feu/moodle/mod/zoom/lib.php(541): calendar_event::create(Object(stdClass))
#2 /repositories/dev/Moodle283feu/moodle/mod/zoom/backup/moodle2/restore_zoom_stepslib.php(92): zoom_calendar_item_update(Object(stdClass))
#3 /repositories/dev/Moodle283feu/moodle/backup/util/plan/restore_structure_step.class.php(137): restore_zoom_activity_structure_step->process_zoom(Object(stdClass))
#4 /repositories/dev/Moodle283feu/moodle/backup/util/helper/restore_structure_parser_processor.class.php(123): restore_structure_step->process(Array)
#5 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/processors/grouped_parser_processor.class.php(178): restore_structure_parser_processor->dispatch_chunk(Array)
#6 /repositories/dev/Moodle283feu/moodle/backup/util/helper/restore_structure_parser_processor.class.php(111): grouped_parser_processor->postprocess_chunk(Array)
#7 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/processors/simplified_parser_processor.class.php(148): restore_structure_parser_processor->postprocess_chunk(Array)
#8 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/processors/progressive_parser_processor.class.php(92): simplified_parser_processor->process_chunk(Array)
#9 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/progressive_parser.class.php(190): progressive_parser_processor->receive_chunk(Array)
#10 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/progressive_parser.class.php(278): progressive_parser->publish(Array)
#11 [internal function]: progressive_parser->end_tag(Resource id #123782, 'zoom')
#12 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/progressive_parser.class.php(179): xml_parse(Resource id #123782, '<?xml version="...', true)
#13 /repositories/dev/Moodle283feu/moodle/backup/util/xml/parser/progressive_parser.class.php(158): progressive_parser->parse('<?xml version="...', true)
#14 /repositories/dev/Moodle283feu/moodle/backup/util/plan/restore_structure_step.class.php(110): progressive_parser->process()
#15 /repositories/dev/Moodle283feu/moodle/backup/util/plan/base_task.class.php(181): restore_structure_step->execute()
#16 /repositories/dev/Moodle283feu/moodle/backup/moodle2/restore_activity_task.class.php(219): base_task->execute()
#17 /repositories/dev/Moodle283feu/moodle/backup/util/plan/base_plan.class.php(191): restore_activity_task->execute()
#18 /repositories/dev/Moodle283feu/moodle/backup/util/plan/restore_plan.class.php(168): base_plan->execute()
#19 /repositories/dev/Moodle283feu/moodle/backup/controller/restore_controller.class.php(408): restore_plan->execute()
#20 /repositories/dev/Moodle283feu/moodle/admin/cli/restore_backup.php(100): restore_controller->execute_plan()
#21 {main}
== Temporäre Dateien löschen ==
Default exception handler: Fehler: Sie haben aktuell kein Recht, den Termin zu aktualisieren. Debug:
Error code: generalexceptionmessage
* line 106 of /admin/cli/restore_backup.php: moodle_exception thrown

!!! Fehler: Sie haben aktuell kein Recht, den Termin zu aktualisieren. !!!
!!
Error code: generalexceptionmessage !!
!! Stack trace: * line 106 of /admin/cli/restore_backup.php: moodle_exception thrown
```

In my opinion it would be better that the CLI script runs as the main admin, but until then the script can't be used to restore a mod_zoom course. I don't know what side effects exist when just changing the line to

```
calendar_event::create($newevent, false);
```
What do you think?

**Comment by jrchamp** [comment]
Thanks @danowar2k! I think that you are correct that the restore_backup.php script should run as the admin user. However, I also think that we have already done sufficient permissions checks prior to running the calendar_event::create() call, so it should be safe for us to pass `false` as the second parameter. Thank you so much for bringing this to our attention.

Reference: https://github.com/moodle/moodle/blob/d76e211be6ae65fe3982ad97f3fe5c879a7b2daa/calendar/lib.php#L942-L944
